<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Customer\Dto\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\NorthWind.Infrastructure\NorthWind.Infrastructure.csproj" />
    </ItemGroup>

</Project>
